# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: 'windows-2019'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '13.x'
  displayName: 'Install Node.js'

- script: chcp
  displayName: 'Show current codepage'

- script: chcp 65001
  displayName: 'Change codepage to Unicode (UTF-8 without BOM)'

- script: yarn
  displayName: 'Restore packages'

- script: npm run build
  displayName: 'Build website'

- task: CopyFiles@2
  displayName: 'Copy to ArtifactStagingDirectory'
  inputs:
    SourceFolder: './public'
    Contents: '**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Build Artifacts'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'